added a washing dishes chore
onja-madagascar/chores pull request #12
Opened 2020-01-24 11:44 UTC by mitia-anah

Hello team,

please have a look at my PR.I added one file,please check it and  change it if need be.

Thank you .

2020-01-24 12:35 UTC, moro-patana requested changes

2020-01-24 12:35 UTC, moro-patana commented on washing-dishes .md
> +# Whashing dishes
oops! your speliing is wrong

2020-01-24 12:52 UTC, mitia-anah commented on washing-dishes .md
> +# Whashing dishes
can find my mistake

2020-01-24 12:52 UTC, mitia-anah commented on washing-dishes .md
> +# Whashing dishes
what is my mistake pleas?

2020-01-24 12:52 UTC, mitia-anah commented on washing-dishes .md
> +# Whashing dishes
Oops ,sorry about the mistake on my file name,it should not have space.

2020-01-24 12:52 UTC, mitia-anah commented on washing-dishes .md
> +# Whashing dishes
Thanks for checking my PR.

2020-01-24 13:03 UTC, mitia-anah reviewed
Please tell me what the mistake was.

2020-01-24 13:03 UTC, mitia-anah commented on washing-dishes .md
> +# Whashing dishes
Thank you dear for checking my PR.

2020-01-25 13:33 UTC, Ny-Rianala approved these changes

2020-01-25 13:34 UTC, merged

2020-01-25 13:34 UTC, Ny-Rianala commented
> Hello team,
> 
> please have a look at my PR.I added one file,please check it and change it if need be.
> 
> Thank you .

2020-01-25 13:35 UTC, Ny-Rianala commented
Looks good?