added a washing pot
onja-madagascar/chores pull request #19
Opened 2020-01-24 11:45 UTC by lightme-fan

Hi everyone, 

could you look at my PR, I add one file, I am happy if you could make a change for it.

Thank in advance

2020-01-24 12:33 UTC, bakozetra requested changes

2020-01-24 12:33 UTC, bakozetra commented on README.md
> +git# chores
oops this was not meant to happen

2020-01-24 12:33 UTC, bakozetra commented on cleaning rice.md
> +# Cleaning rice
This file name should not have spaces

2020-01-24 12:39 UTC, lightme-fan commented on README.md
> +git# chores
Thank you

2020-01-25 08:18 UTC, lightme-fan commented
closed this because Kati's pull request

2020-01-25 08:18 UTC, closed without merging