Added a washing-pots chore
onja-madagascar/chores pull request #8
Opened 2020-01-24 11:44 UTC by Voninkazo

Hey team,
Please have a look at my PR.I added one file,happy to change if needs be.

Thanks,

Sandy

2020-01-24 12:38 UTC, Tanosimboangy requested changes

2020-01-24 12:38 UTC, Tanosimboangy commented on washing-pots.md
> +# Washing pots
Thanks to your correct writing

2020-01-24 12:42 UTC, Voninkazo commented on washing-pots.md
> +# Washing pots
For a pleasure.

2020-01-25 11:51 UTC, lightme-fan commented
we wanna merge this pull request, would you mind to approve this?

2020-01-27 06:22 UTC, closed without merging